name: GitHub Pages Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Packages
      run: npm i

    - name: Build
      run: npm run build
    
    - name: Save Dist Folder
      run: |
        git add -f dist/
        git stash

    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Apply Stash
      run: git stash pop --quiet || exit 0

    - name: Resolve Conflicts
      run: git checkout --theirs dist/

    - name: Pull Actual Files From master
      run: |
        git checkout master -- icons/
        git checkout master -- browserconfig.xml
        git checkout master -- index.html
        git checkout master -- manifest.json
    
    - name: Add Files to Commit
      run: git add -f dist/ icons/ browserconfig.xml index.html manifest.json
    
    - name: Commit
      run: |
        git config --local user.email "GLEBR1K@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git diff-index --quiet HEAD || git commit -m "GitHub Pages automated update"
    
    - name: Push to origin/gh-pages
      uses: ad-m/github-push-action@master
      with:
        branch: 'gh-pages'
        github_token: ${{ secrets.GITHUB_TOKEN }}
